### ISSUE TITLE
Add support for reading Excel files into DataFrame

### ISSUE THREAD

**Issue by Zavster** [zavtech/morpheus-core#15]

**Comment by dgunning** [comment]
Xavier ,

I have implemented reading from Excel into Morpheus DataFrames on my local branch of morpheus-core. Can I submit a pull request?

Dwight Gunning

**Comment by Zavster** [comment]
Sure, that would be awesome, thanks Dwight!

**Comment by dgunning** [comment]
Nice. Can you grant me create and push to a branch, or can you create a branch and grant me access to it. Then I can create a pull request. Alternatively I can create a pull request based on a fork, but i have already cloned and created a local branch.

Thanks

**Comment by Zavster** [comment]
Hey Dwight, please create a fork and then just push your branch to your fork, and you will then be able to raise a PR which I can review / merge. That's generally the workflow I use myself.

**Comment by dgunning** [comment]
Created pull request

**Comment by Zavster** [comment]
These changes have been merged and released to Maven Central as 0.9.21. Thanks
