### ISSUE TITLE
Update Univocity Parsers version to 2.X.X

### ISSUE THREAD

**Issue by dgunning** [zavtech/morpheus-core#82]
Morpheus uses Univocity Parser library version 1.5.9 which was released in 2015. This cause an issue for using both Morpheus and the latest version of Univocity in the same project.

The latest univocity version also has some changes to the CharAppender that might be useful for helping to implement Excel Parsing.

The Morpheus tests pass for me with univocity version bumped to 2.5.9.

**Comment by Zavster** [comment]
Thanks for pointing this out. I have released morpheus-core 0.9.20 to Maven with upgrades to all the latest third party libs. The commit is linked below.
https://github.com/zavtech/morpheus-core/commit/3e60d7fa91893fc94c356c660f536127852fe6be
