### ISSUE TITLE
Add setting for Columns size

### ISSUE THREAD

**Issue by Ebalaitung** [zavtech/morpheus-core#98]
Hello Morpheus team.
Currently I've tried to load csv file with 30_000x2000 features using Morpheus  DataFrame, but got stuck into univocity CsvParser maxColumns hard coded to be 10_000.
I think there should be possibility to configure it via options.

**Comment by Zavster** [comment]
This has been merged, thanks for the PR - I will try push an updated build to Maven Central by tonight.

**Comment by Ebalaitung** [comment]
tnx!
